### ISSUE TITLE
Error: invalid_grant when local date is wrong

### ISSUE THREAD

**Issue by rozumny** [google/google-auth-library-nodejs#129]
hello, any idea how to fix it?

node_modules/playup/cli.js --auth ./build/api.json --track alpha  signed.apk

Error: invalid_grant
    at Request._callback (/Users/rozumny/development/mm3/node_modules/gtoken/lib/index.js:215:34)
    at Request.self.callback (/Users/rozumny/development/mm3/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/Users/rozumny/development/mm3/node_modules/request/request.js:1081:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/Users/rozumny/development/mm3/node_modules/request/request.js:1001:12)
    at IncomingMessage.g (events.js:291:16)
    at emitNone (events.js:91:20)

**Comment by lukesneeringer** [comment]
Hi @rozumny,
Can you give us more information to help us troubleshoot this?

**Comment by rozumny** [comment]
hi, I found the problem. It happens when your server time is out of sync.

**Comment by ofrobots** [comment]
I remember seeing the same issue once in the past caused by a docker bug where, over time, the timestamp inside the docker VMs would drift, eventually to cause auth errors.

I wonder if there is an easy way for us to detect this scenario and present a more meaningful error message. If the response has a timestamp that is significantly (hours) away from our local timestamp, for example.

**Comment by JustinBeckwith** [comment]
Here is the error message you get today:

```
Error: invalid_grant: Invalid JWT: Token must be a short-lived token (60 minutes) and in a reasonable timeframe. Check your iat and exp values and use a clock with skew to account for clock differences between systems.
    at /Users/beckwith/Code/google-auth-library-nodejs/node_modules/gtoken/build/src/index.js:255:35
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

I think that's pretty reasonable :) Let me know if there is something else you think we should do here.
