### ISSUE TITLE
Wrong recipient, payload audience != requiredAudience

### ISSUE THREAD

**Issue by dinesh-bhardwaj** [google/google-auth-library-nodejs#222]
I have integrated Google sign in and getting Token from it, now when i vertify the token, i always get this error. I tried many times but nothing works, and i always get this error
```
Error: Wrong recipient, payload audience != requiredAudience
    at OAuth2Client.verifySignedJwtWithCerts (/home/XXX/node_modules/google-auth-library/lib/auth/oauth2client.js:499:23)
    at OAuth2Client.<anonymous> (/home/XXX/node_modules/google-auth-library/lib/auth/oauth2client.js:361:31)
    at /home/XXX/node_modules/google-auth-library/lib/auth/oauth2client.js:407:13
    at Request._callback (/home/XXX/node_modules/google-auth-library/lib/transporters.js:113:17)
    at Request.self.callback (/home/XXX/node_modules/request/request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/home/XXX/node_modules/request/request.js:1163:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/home/XXX/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
```

I Followed this document => **https://developers.google.com/identity/sign-in/web/backend-auth**

the Code i am using to verify 
```
var GoogleAuth = require('google-auth-library');
var auth = new GoogleAuth;
var client = new auth.OAuth2(CLIENT_ID, '', '');
client.verifyIdToken(
    token,
    CLIENT_ID,
    // Or, if multiple clients access the backend:
    //[CLIENT_ID_1, CLIENT_ID_2, CLIENT_ID_3],
    function(e, login) {
      var payload = login.getPayload();
      var userid = payload['sub'];
      // If request specified a G Suite domain:
      //var domain = payload['hd'];
    });
```

**Comment by JustinBeckwith** [comment]
Greetings!  Could you take a look at this sample, and see if anything pops out?
https://github.com/google/google-auth-library-nodejs/pull/219/files#diff-62502f095646cbe2651801cf13671479

In your code - where are you getting the value `token` from?  Could you share that?

In taking a look at your error message - we're able to parse the token, we're pulling out the fields in the payload, and the audience field just doesn't seem to match.  What kind of a keyfile are you using to acquire the audience / CLIENT_ID?  Is it using service account credentials, or OAuth2?

**Comment by JustinBeckwith** [comment]
If the previous comment doesn't help unblock you, feel free to leave feedback and we can re-open this issue :)
