### ISSUE TITLE
Can't find module 'gcp-metadata'

### ISSUE THREAD

**Issue by zcaceres** [google/google-auth-library-nodejs#295]
As of about a half hour ago, I can no longer deploy a service that uses google-auth-library.

I get this when I run my tests (in Mocha). There were no dependency changes in the project. Has anyone seen this suddenly pop up?

Error: Cannot find module 'gcp-metadata'
    at Function.Module._resolveFilename (module.js:476:15)
    at Function.Module._load (module.js:424:25)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/ubuntu/lorem-restapi/node_modules/googleapis/node_modules/google-auth-library/build/src/auth/googleauth.js:55:19)

**Comment by zcaceres** [comment]
Just noticed that this library was updated 37 min ago. My last successful build was also 37 minutes ago, and each once since has failed. Or maybe I'm just seeing a coincidence??

**Comment by JustinBeckwith** [comment]
Apologies for this one folks.  Hard to catch those ones with tests :(   We just cut a new release, and 1.3.1 should be out in a few minutes.

**Comment by zcaceres** [comment]
Thanks for the quick fix! Thought maybe I had gone crazy.
