### ISSUE TITLE
Support for OAuth2 implicit flow/client-side apps flow

### ISSUE THREAD

**Issue by JustinBeckwith** [google/google-auth-library-nodejs#299]
_From @bnookala on March 9, 2016 9:8_

I'm building a client side application using the Calendar API. Since I don't want to bundle a client secret, I'm currently leaving it out when instantiating the OAuth client ie: 

`this.oauthClient = new OAuth2(this.oa2.clientID, undefined, this.oa2.redirectURI);`

This appears to work fine until the client token is requested with the auth code from the redirected URL via `this.oauthClient.getToken`, whereupon it fails with this error and trace:

```
Error: invalid_request
    at Request._callback (/Users/bhargav/code/waffle/node_modules/google-auth-library/lib/transporters.js:78:15)
    at Request.self.callback (/Users/bhargav/code/waffle/node_modules/google-auth-library/node_modules/request/request.js:198:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/Users/bhargav/code/waffle/node_modules/google-auth-library/node_modules/request/request.js:1057:14)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/Users/bhargav/code/waffle/node_modules/google-auth-library/node_modules/request/request.js:1003:12)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at doNTCallback2 (node.js:465:9)
    at process._tickCallback (node.js:379:17)
```

Adding the client secret to the the OAuth2 instantiation line appears to work swimmingly, and an access token is able to be retrieved.

Is there any intent for this library to support the OAuth2 client side application flow as [described by this doc](https://developers.google.com/identity/protocols/OAuth2UserAgent)?

_Copied from original issue: google/google-api-nodejs-client#529_

**Comment by JustinBeckwith** [comment]
_From @zweicoder on May 5, 2016 7:7_

Any updates on this? I'm encountering the same problem trying to avoid packaging the `client_secret` in my `Electron` app

**Comment by JustinBeckwith** [comment]
I don't have any answers here, but this is a really good question.  Wondering if @jonparrott or @anthmgoogle do :)

**Comment by JustinBeckwith** [comment]
We figured out the magic trick here.  When you generate your OAuth2 credentials in the developer console, you need to choose the `iOS` application type:
![image](https://user-images.githubusercontent.com/534619/36553844-3f9a863c-17b2-11e8-904a-29f6cd5f807a.png)

If you do that - then you don't need to pass a `client_secret` into the OAuth2 constructor, and everything will still work :)

I'm keeping this open so I can write a snippet in the docs to cover the topic later.

**Comment by gscoon** [comment]
@JustinBeckwith Thanks for your help here.  I'm curious though - what would prevent a malicious user from stealing your *clientID* and making tons of requests pretending to be your app?
