### ISSUE TITLE
GCF: `getCredentials` returning "Failure from metadata server."

### ISSUE THREAD

**Issue by stephenplusplus** [google/google-auth-library-nodejs#321]
*Originally reported here: https://github.com/googleapis/nodejs-storage/issues/150*

I'm receiving this error in GCF using `google-auth-library`@^1.3.1:

```js
Error: Failure from metadata server.
    at GoogleAuth.<anonymous> (/user_code/node_modules/google-auth-library/build/src/auth/googleauth.js:634:35)
    at step (/user_code/node_modules/google-auth-library/build/src/auth/googleauth.js:47:23)
    at Object.next (/user_code/node_modules/google-auth-library/build/src/auth/googleauth.js:28:53)
    at fulfilled (/user_code/node_modules/google-auth-library/build/src/auth/googleauth.js:19:58)
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)
```

Cloud function source:

```js
const GoogleAuth = require('google-auth-library').GoogleAuth

exports.test = function test (req, res) {
  function end(err) {
    console.error(err)
    res.status(500).end()
  }

  const authClient = new GoogleAuth()
  authClient.getApplicationDefault(err => {
    if (err) return end(err)

    authClient.getCredentials((err, credentials) => {
      if (err) return end(err)
      console.log(credentials)
      res.send('Ok')
    })
  })
}
```

Am I doing anything wrong this way?

**Comment by JustinBeckwith** [comment]
So far as I can tell, this is a bug with the implementation of the metadata server in GCF  😨 I opened a bug on their side, and I'll report back when I have more info!

**Comment by stephenplusplus** [comment]
Thanks for the quick research, fix, and release!
