### ISSUE TITLE
Unable to proxy through HTTPS_PROXY

### ISSUE THREAD

**Issue by skyser2003** [google/google-auth-library-nodejs#331]
Hello, I'm trying to use this library with HTTPS_PROXY env variable set,
but no matter what I do I couldn't get it working.

Error message is as following:

> "Error: Failed to retrieve verification certificates: Error: write EPROTO 101057795:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:openssl\ssl\s23_clnt.c:825:
>     at OAuth2Client.<anonymous> (D:\Projects\baseball_app_server\jsOut\sphinx\node_modules\google-auth-library\build\src\auth\oauth2client.js:515:31)
>     at step (D:\Projects\baseball_app_server\jsOut\sphinx\node_modules\google-auth-library\build\src\auth\oauth2client.js:57:23)
>     at Object.throw (D:\Projects\baseball_app_server\jsOut\sphinx\node_modules\google-auth-library\build\src\auth\oauth2client.js:38:53)
>     at rejected (D:\Projects\baseball_app_server\jsOut\sphinx\node_modules\google-auth-library\build\src\auth\oauth2client.js:30:65)
>     at <anonymous>"	string

I use squid 3.5 as proxy server, and I am using the same proxy server to proxy facebook oauth2(https://graph.facebook.com), and it works perfectly well.

I use HTTPS_PROXY env variable to provide proxy information to the library.
For facebook, that env variable doesn't work, so I used the method described here([https://github.com/feathersjs/authentication-oauth2/issues/62]);

And this is the squid log:

> 1521627064.515    572 172.20.78.188 TCP_TUNNEL/200 4189 CONNECT graph.facebook.com:443 - HIER_DIRECT/31.13.78.13 -
> 1521627070.050      0 172.20.78.188 TAG_NONE/400 4408 NONE error:invalid-request - HIER_NONE/- text/html

First line is for facebook oauth2 proxy, and second line is for google oauth2 proxy.  As it says, it doesn't receive any information at all, meaning library itself is sending wrong information to proxy server.

**Comment by skyser2003** [comment]
Tried a workaround, but it gives the same error.

```
const oauthCli = new OAuth2Client( { ... } );

const transporter = this.oauthCli.transporter;
const originalRequest = transporter.request;

const proxyConfig = transporter.configure({
    proxy: {
        host: "localhost",
        port: 3128
    },
    headers: {
        "cache-control": "no-cache"
    }
});

const requestInject = function (config, callback?) {
    Object.assign(config, proxyConfig);

    return originalRequest.bind(transporter)(config, callback);
};

try {
    transporter["request"] = requestInject as any;
} catch (e) {
    console.error(e);
}
```

**Comment by skyser2003** [comment]
Seems like axios issue. 

[Request to HTTPS with HTTP proxy fails]
https://github.com/axios/axios/issues/925
