### ISSUE TITLE
Cannot authorize with JWT 

### ISSUE THREAD

**Issue by Viatorus** [google/google-auth-library-nodejs#441]
I just used the basic example from the Readme.

```js
const {JWT} = require('google-auth-library');
const keys = require('./jwt.keys.json');

async function main() {
  const client = new JWT(
    keys.client_email,
    null,
    keys.private_key,
    ['https://www.googleapis.com/auth/cloud-platform'],
  );
  await client.authorize();
  const url = `https://www.googleapis.com/dns/v1/projects/${keys.project_id}`;
  const res = await client.request({url});
  console.log(res.data);
}

main().catch(console.error);
```

Tested with v1.6.1 and the current master (31faf8b6028b2a20ecfa9e12705839bf3b2490cb).

After a long timeout, I get the following error:
```js
{ Error: connect ETIMEDOUT 172.217.19.74:443
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
  code: 'ETIMEDOUT',
  errno: 'ETIMEDOUT',
  syscall: 'connect',
  address: '172.217.19.74',
  port: 443,
  config: 
   { adapter: [Function: httpAdapter],
     transformRequest: { '0': [Function: transformRequest] },
     transformResponse: { '0': [Function: transformResponse] },
     timeout: 0,
     xsrfCookieName: 'XSRF-TOKEN',
     xsrfHeaderName: 'X-XSRF-TOKEN',
     maxContentLength: -1,
     validateStatus: [Function: validateStatus],
     headers: 
      { Accept: 'application/json, text/plain, */*',
        'Content-Type': 'application/x-www-form-urlencoded',
        'User-Agent': 'axios/0.18.0',
        'Content-Length': 726 },
     method: 'post',
     url: 'https://www.googleapis.com/oauth2/v4/token',
     data: 'grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Ajwt-bearer&assertion=>...<' },
  request: 
   Writable {
     _writableState: 
      WritableState {
        objectMode: false,
        highWaterMark: 16384,
        finalCalled: false,
        needDrain: false,
        ending: false,
        ended: false,
        finished: false,
        destroyed: false,
        decodeStrings: true,
        defaultEncoding: 'utf8',
        length: 0,
        writing: false,
        corked: 0,
        sync: true,
        bufferProcessing: false,
        onwrite: [Function: bound onwrite],
        writecb: null,
        writelen: 0,
        bufferedRequest: null,
        lastBufferedRequest: null,
        pendingcb: 0,
        prefinished: false,
        errorEmitted: false,
        bufferedRequestCount: 0,
        corkedRequestsFree: [Object] },
     writable: true,
     domain: null,
     _events: 
      { response: [Function: handleResponse],
        error: [Function: handleRequestError] },
     _eventsCount: 2,
     _maxListeners: undefined,
     _options: 
      { protocol: 'https:',
        maxRedirects: 21,
        maxBodyLength: 10485760,
        path: '/oauth2/v4/token',
        method: 'post',
        headers: [Object],
        agent: undefined,
        auth: undefined,
        hostname: 'www.googleapis.com',
        port: null,
        nativeProtocols: [Object],
        pathname: '/oauth2/v4/token' },
     _redirectCount: 0,
     _redirects: [],
     _requestBodyLength: 726,
     _requestBodyBuffers: [ [Object] ],
     _onNativeResponse: [Function],
     _currentRequest: 
      ClientRequest {
        domain: null,
        _events: [Object],
        _eventsCount: 6,
        _maxListeners: undefined,
        output: [],
        outputEncodings: [],
        outputCallbacks: [],
        outputSize: 0,
        writable: true,
        _last: true,
        upgrading: false,
        chunkedEncoding: false,
        shouldKeepAlive: false,
        useChunkedEncodingByDefault: true,
        sendDate: false,
        _removedConnection: false,
        _removedContLen: false,
        _removedTE: false,
        _contentLength: null,
        _hasBody: true,
        _trailer: '',
        finished: false,
        _headerSent: true,
        socket: [Object],
        connection: [Object],
        _header: 'POST /oauth2/v4/token HTTP/1.1\r\nAccept: application/json, text/plain, */*\r\nContent-Type: application/x-www-form-urlencoded\r\nUser-Agent: axios/0.18.0\r\nContent-Length: 726\r\nHost: www.googleapis.com\r\nConnection: close\r\n\r\n',
        _onPendingData: [Function: noopPendingOutput],
        agent: [Object],
        socketPath: undefined,
        timeout: undefined,
        method: 'POST',
        path: '/oauth2/v4/token',
        _ended: false,
        res: null,
        aborted: undefined,
        timeoutCb: null,
        upgradeOrConnect: false,
        parser: null,
        maxHeadersCount: null,
        _redirectable: [Circular],
        [Symbol(outHeadersKey)]: [Object] },
     _currentUrl: 'https://www.googleapis.com/oauth2/v4/token' },
  response: undefined }
```

**Comment by abhishekwfd** [comment]
+1 Having the same issue.

**Comment by abhishekwfd** [comment]
> I just used the basic example from the Readme.
> 
> ```js
> const {JWT} = require('google-auth-library');
> const keys = require('./jwt.keys.json');
> 
> async function main() {
>   const client = new JWT(
>     keys.client_email,
>     null,
>     keys.private_key,
>     ['https://www.googleapis.com/auth/cloud-platform'],
>   );
>   await client.authorize();
>   const url = `https://www.googleapis.com/dns/v1/projects/${keys.project_id}`;
>   const res = await client.request({url});
>   console.log(res.data);
> }
> 
> main().catch(console.error);
> ```
> 
> Tested with v1.6.1 and the current master ([31faf8b](https://github.com/googleapis/google-auth-library-nodejs/commit/31faf8b6028b2a20ecfa9e12705839bf3b2490cb)).
> 
> After a long timeout, I get the following error:
> 
> ```js
> { Error: connect ETIMEDOUT 172.217.19.74:443
>     at Object._errnoException (util.js:992:11)
>     at _exceptionWithHostPort (util.js:1014:20)
>     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
>   code: 'ETIMEDOUT',
>   errno: 'ETIMEDOUT',
>   syscall: 'connect',
>   address: '172.217.19.74',
>   port: 443,
>   config: 
>    { adapter: [Function: httpAdapter],
>      transformRequest: { '0': [Function: transformRequest] },
>      transformResponse: { '0': [Function: transformResponse] },
>      timeout: 0,
>      xsrfCookieName: 'XSRF-TOKEN',
>      xsrfHeaderName: 'X-XSRF-TOKEN',
>      maxContentLength: -1,
>      validateStatus: [Function: validateStatus],
>      headers: 
>       { Accept: 'application/json, text/plain, */*',
>         'Content-Type': 'application/x-www-form-urlencoded',
>         'User-Agent': 'axios/0.18.0',
>         'Content-Length': 726 },
>      method: 'post',
>      url: 'https://www.googleapis.com/oauth2/v4/token',
>      data: 'grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Ajwt-bearer&assertion=>...<' },
>   request: 
>    Writable {
>      _writableState: 
>       WritableState {
>         objectMode: false,
>         highWaterMark: 16384,
>         finalCalled: false,
>         needDrain: false,
>         ending: false,
>         ended: false,
>         finished: false,
>         destroyed: false,
>         decodeStrings: true,
>         defaultEncoding: 'utf8',
>         length: 0,
>         writing: false,
>         corked: 0,
>         sync: true,
>         bufferProcessing: false,
>         onwrite: [Function: bound onwrite],
>         writecb: null,
>         writelen: 0,
>         bufferedRequest: null,
>         lastBufferedRequest: null,
>         pendingcb: 0,
>         prefinished: false,
>         errorEmitted: false,
>         bufferedRequestCount: 0,
>         corkedRequestsFree: [Object] },
>      writable: true,
>      domain: null,
>      _events: 
>       { response: [Function: handleResponse],
>         error: [Function: handleRequestError] },
>      _eventsCount: 2,
>      _maxListeners: undefined,
>      _options: 
>       { protocol: 'https:',
>         maxRedirects: 21,
>         maxBodyLength: 10485760,
>         path: '/oauth2/v4/token',
>         method: 'post',
>         headers: [Object],
>         agent: undefined,
>         auth: undefined,
>         hostname: 'www.googleapis.com',
>         port: null,
>         nativeProtocols: [Object],
>         pathname: '/oauth2/v4/token' },
>      _redirectCount: 0,
>      _redirects: [],
>      _requestBodyLength: 726,
>      _requestBodyBuffers: [ [Object] ],
>      _onNativeResponse: [Function],
>      _currentRequest: 
>       ClientRequest {
>         domain: null,
>         _events: [Object],
>         _eventsCount: 6,
>         _maxListeners: undefined,
>         output: [],
>         outputEncodings: [],
>         outputCallbacks: [],
>         outputSize: 0,
>         writable: true,
>         _last: true,
>         upgrading: false,
>         chunkedEncoding: false,
>         shouldKeepAlive: false,
>         useChunkedEncodingByDefault: true,
>         sendDate: false,
>         _removedConnection: false,
>         _removedContLen: false,
>         _removedTE: false,
>         _contentLength: null,
>         _hasBody: true,
>         _trailer: '',
>         finished: false,
>         _headerSent: true,
>         socket: [Object],
>         connection: [Object],
>         _header: 'POST /oauth2/v4/token HTTP/1.1\r\nAccept: application/json, text/plain, */*\r\nContent-Type: application/x-www-form-urlencoded\r\nUser-Agent: axios/0.18.0\r\nContent-Length: 726\r\nHost: www.googleapis.com\r\nConnection: close\r\n\r\n',
>         _onPendingData: [Function: noopPendingOutput],
>         agent: [Object],
>         socketPath: undefined,
>         timeout: undefined,
>         method: 'POST',
>         path: '/oauth2/v4/token',
>         _ended: false,
>         res: null,
>         aborted: undefined,
>         timeoutCb: null,
>         upgradeOrConnect: false,
>         parser: null,
>         maxHeadersCount: null,
>         _redirectable: [Circular],
>         [Symbol(outHeadersKey)]: [Object] },
>      _currentUrl: 'https://www.googleapis.com/oauth2/v4/token' },
>   response: undefined }
> ```

Hi Viatorus, how come you resolved this issue. I am using v4 google nodejs client and facing this issue.

**Comment by Viatorus** [comment]
I didn't. I just moved on without nodejs and Google API.

**Comment by JustinBeckwith** [comment]
Based on that response you're behind a proxy (the 172 addy) Have you configured it with the right env vars?
